#!/bin/sh 
echo "HDF5_CACHE_STORAGE_TYPE SSD\nHDF5_CACHE_STORAGE_PATH SSD\nHDF5_CACHE_STORAGE_SCOPE LOCAL\nHDF5_CACHE_STORAGE_SIZE 128755813888000\nHDF5_CACHE_WRITE_BUFFER_SIZE 17179869184" > conf1.dat

export HDF5_PLUGIN_PATH=/Users/zhenghh/Documents/Research/ExaHDF5/exahdf5_sdk/soft//hdf5/vol/lib
export HDF5_VOL_CONNECTOR="cache_ext config=conf1.dat;under_vol=512;under_info={under_vol=0;under_info={}}"
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$HDF5_PLUGIN_PATH
export DEBUG=2
for opt in 'yes' 'no'
do
    echo "Testing"
    HDF5_CACHE_WR=$opt mpirun -np 2 ./test_dataset
    HDF5_CACHE_WR=$opt mpirun -np 2 ./test_group
    HDF5_CACHE_WR=$opt mpirun -np 2 ./test_file
done
    


